data:
  target: train.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    train:
      target: edit_dataset.EditDataset
      params:
        path: saved_images_2
        split: train
        min_resize_res: 256
        max_resize_res: 256
        crop_res: 256
        flip_prob: 0.5
        prompt_option: output
    validation:
      target: edit_dataset.EditDataset
      params:
        path: saved_images_2
        split: val
        min_resize_res: 256
        max_resize_res: 256
        crop_res: 256
        prompt_option: output

